[workspace]
members = ["daemon", "common", "gui"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"

[workspace.dependencies]
egui = { version = "0.29", default-features = false }
eframe = { version = "0.29", default-features = false }
egui_extras = { version = "0.29", default-features = false }
egui_plot = { version = "0.29", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
zbus = "5"
tokio = "1"
anyhow = "1.0"
systemstat = "0.2"
once_cell = "1"
nix = "0.29"
libloading = "0.8"
webbrowser = "1.0"
lapsphere-common = { path = "./common" }
