[package]
name = "lapsphere-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lapsphere-common.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
chrono.workspace = true
zbus.workspace = true
tokio = { workspace = true, features = ["full"] }
libc = "0.2"
nix = { workspace = true, features = ["ioctl", "signal"] }
nvml-wrapper = "0.11.0"
once_cell.workspace = true
systemstat.workspace = true
