#!/bin/bash
set -e

case "$1" in
    configure)
        # Reload DBus configuration
        dbus-send --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig || true
        
        # Update icon cache
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -q -f /usr/share/icons/hicolor || true
        fi
        
        # Update desktop database
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database -q /usr/share/applications || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
