#!/bin/sh
# Build the layer, then stamp the build identity into the binary so that
# `vkNegotiateLoaderLayerInterfaceVersion` can print it.
#
# Why this exists: the manifest references the .so by absolute path, so
# "cargo build finished" does not imply "this is the code that ran". Twice in
# the spike a stale build was mistaken for a behavioural result. Now the layer
# prints its own build id, and the run script compares it against
# /proc/<pid>/maps.
set -e
here=$(cd "$(dirname "$0")" && pwd)
cd "$here"

so="$here/target/release/liblapsphere_frames_layer.so"

# 1. a stamp that changes on every source edit
stamp=$(cat src/lib.rs src/shm.rs src/vkraw.rs | sha256sum | cut -c1-12)
mtime=$(date -r src/lib.rs '+%Y-%m-%dT%H:%M:%S')
cat > src/buildid.rs <<EOF
// Generated by build.sh -- do not edit.
pub const BUILD_ID: &str = "$stamp";
pub const BUILD_MTIME: &str = "$mtime";
EOF

LAPSPHERE_BUILD_ID="$stamp" LAPSPHERE_BUILD_MTIME="$mtime" \
  cargo build --release "$@"

echo "build_id=$stamp  source_mtime=$mtime"
ls -la "$so"