name: Rust

on:
  push:
    branches:
      - main
      - egui_mod
  pull_request:
    branches:
      - main
      - egui_mod

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y debhelper devscripts build-essential
          sudo apt-get install -y \
            cargo \
            rustc \
            libdbus-1-dev \
            pkg-config \
            libgtk-3-dev \
            libadwaita-1-dev \
            libpango1.0-dev \
            libcairo2-dev \
            libgdk-pixbuf-2.0-dev \
            libatk1.0-dev \
            libgraphene-1.0-dev \
            libwayland-dev \
            libxkbcommon-dev

    - name: Clean the project
      run: cargo clean 

    - name: Run tests
      run: cargo test

    - name: Build Debian package
      run: |
          dpkg-buildpackage -b -uc -us
          mkdir artifacts
          cp ../lapsphere_*.deb artifacts/

    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: lapsphere-ubuntu-24.04-deb
        path: artifacts/*.deb
        retention-days: 90

  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Update Arch Linux
      run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel rustup pkgconf dbus gtk3 libadwaita pango cairo gdk-pixbuf2 atk graphene wayland libxkbcommon

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      run: |
          rustup default stable

    - name: Build project
      run: cargo build --release

    - name: Upload Arch binaries
      uses: actions/upload-artifact@v4
      with:
        name: lapsphere-arch-binaries
        path: |
          target/release/lapsphere-daemon
          target/release/lapsphere
        retention-days: 90
